menu:
  主页: / || fas fa-home
  博文 || fa fa-graduation-cap:
    分类: /categories/ || fa fa-archive
    标签: /tags/ || fa fa-tags
    归档: /archives/ || fa fa-folder-open
  生活 || fas fa-list:
    分享: /shuoshuo/ || fa fa-comments-o
    相册: /photos/ || fa fa-camera-retro
    音乐: /music/ || fa fa-music
    影视: /movies/ || fas fa-video
  友链: /links/ || fa fa-link
  留言板: /comment/ || fa fa-paper-plane
  #留言板: /messageboard/ || fa fa-paper-plane
  关于笔者: /about/ || fas fa-heart  

activate_power_mode:
    enable: false
    colorful: true # open particle animation (冒光特效)
    shake: true #  open shake (抖動特效)
    mobile: false

# Mouse click effects: fireworks (鼠標點擊效果: 煙火特效)
fireworks:
    enable: true
    zIndex: 9999 # -1 or 9999
    mobile: false

# Mouse click effects: Heart symbol (鼠標點擊效果: 愛心)
click_heart:
    enable: false
    mobile: false

# Mouse click effects: words (鼠標點擊效果: 文字)
ClickShowText:
    enable: false
    text:
        # - I
        # - LOVE
        # - YOU
    fontSize: 15px
    random: false
    mobile: false

subtitle:
    enable: true
    # Typewriter Effect (打字效果)
    effect: true
    # loop (循環打字)
    loop: true
    # source 調用第三方服務
    # source: true
    # source: 1 https://hitokoto.cn/
    # source: 2 http://yijuzhan.com/
    # source: 3 https://www.jinrishici.com/
    # subtitle 會先顯示 source , 再顯示 sub 的內容
    source: 4
    # 如果關閉打字效果，subtitle 只會顯示 sub 的第一行文字
    sub:
        - 梦想这东西和经典一样 永远不会因为时间而褪色
        - 何其荣幸 何德何能 #注意这里的格式   空格和 '-'
